apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-log-config
  namespace: system
  labels:
    app.kubernetes.io/component: serverless-operator.kyma-project.io
    app.kubernetes.io/instance: operator-log-config
data:
  log-config.yaml: |
    logLevel: info
    logFormat: json

