apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: operator
    app.kubernetes.io/component: serverless-operator.kyma-project.io
    app.kubernetes.io/instance: serverless-operator-deployment
spec:
  selector:
    matchLabels:
      control-plane: operator
      app.kubernetes.io/component: serverless-operator.kyma-project.io
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: operator
        sidecar.istio.io/inject: "false"
        app.kubernetes.io/component: serverless-operator.kyma-project.io
        networking.serverless.kyma-project.io/to-apiserver: allowed
    spec:
      priorityClassName: "operator-priority"
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /operator
          image: controller:latest
          imagePullPolicy: IfNotPresent
          name: manager
          env:
            - name: CHART_PATH
              value: /buildless-module-chart
            - name: SERVERLESS_MANAGER_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: IMAGE_FUNCTION_CONTROLLER
              value: europe-docker.pkg.dev/kyma-project/prod/function-controller:1.9.1
            - name: IMAGE_FUNCTION_BUILD_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/function-build-init:1.9.1
            - name: IMAGE_REGISTRY_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS20
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:1.9.1
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS22
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:1.9.1
            - name: IMAGE_FUNCTION_RUNTIME_PYTHON312
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:1.9.1
            - name: IMAGE_KANIKO_EXECUTOR
              value: europe-docker.pkg.dev/kyma-project/prod/external/gcr.io/kaniko-project/executor:v1.24.0
            - name: IMAGE_REGISTRY
              value: europe-docker.pkg.dev/kyma-project/prod/external/library/registry:3.0.0
            - name: IMAGE_FUNCTION_BUILDLESS_CONTROLLER
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-controller:1.9.1
            - name: IMAGE_FUNCTION_BUILDLESS_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-init:1.9.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
