apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: operator
    app.kubernetes.io/component: serverless-operator.kyma-project.io
    app.kubernetes.io/instance: serverless-operator-deployment
spec:
  selector:
    matchLabels:
      control-plane: operator
      app.kubernetes.io/component: serverless-operator.kyma-project.io
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        rt-cfg.kyma-project.io/alter-img-registry: "true"
        rt-cfg.kyma-project.io/add-img-pull-secret: "true"
        rt-cfg.kyma-project.io/set-fips-mode: "true"
      labels:
        control-plane: operator
        sidecar.istio.io/inject: "false"
        app.kubernetes.io/component: serverless-operator.kyma-project.io
        networking.serverless.kyma-project.io/to-apiserver: allowed
    spec:
      priorityClassName: "operator-priority"
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: log-configuration
          configMap:
            name: operator-log-config
      containers:
        - command:
            - /operator
          image: controller:latest
          imagePullPolicy: IfNotPresent
          name: manager
          env:
            - name: CHART_PATH
              value: /buildless-module-chart
            - name: LOG_CONFIG_PATH
              value: /logconfig/log-config.yaml
            - name: SERVERLESS_MANAGER_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS20
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:main
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS20_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:main #TODO: update to actual nodejs20 fips image when available
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS22
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:main
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS22_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:main #TODO: update to actual nodejs22 fips image when available
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS24
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs24:main
            - name: IMAGE_FUNCTION_RUNTIME_NODEJS24_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs24:main #TODO: update to actual nodejs24 fips image when available
            - name: IMAGE_FUNCTION_RUNTIME_PYTHON312
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:main
            - name: IMAGE_FUNCTION_RUNTIME_PYTHON312_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:main #TODO: update to actual python312 fips image when available
            # Python314 is not yet available, but we already prepare for it by adding the env vars with the expected image references.
            # Once the images are available, the values should be updated to point to the actual python314 images.
            - name: IMAGE_FUNCTION_RUNTIME_PYTHON314
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python314:main
            - name: IMAGE_FUNCTION_RUNTIME_PYTHON314_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python314:main #TODO: update to actual python314 fips image when available
            - name: IMAGE_FUNCTION_BUILDLESS_CONTROLLER
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-controller:main
            - name: IMAGE_FUNCTION_BUILDLESS_CONTROLLER_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-controller:main
            - name: IMAGE_FUNCTION_BUILDLESS_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-init:main
            - name: IMAGE_FUNCTION_BUILDLESS_INIT_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/function-buildless-init:main
            # Images used by serverless running in legacy mode (without buildless)
            - name: IMAGE_FUNCTION_CONTROLLER
              value: europe-docker.pkg.dev/kyma-project/prod/function-controller:main
            - name: IMAGE_FUNCTION_BUILD_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/function-build-init:main
            - name: IMAGE_REGISTRY_INIT
              value: europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d
            - name: IMAGE_KANIKO_EXECUTOR
              value: europe-docker.pkg.dev/kyma-project/prod/external/gcr.io/kaniko-project/executor:v1.24.0
            - name: IMAGE_REGISTRY
              value: europe-docker.pkg.dev/kyma-project/prod/external/library/registry:3.0.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          volumeMounts:
            - name: log-configuration
              mountPath: /logconfig
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
