apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: serverless-priority
  labels:
    kyma-project.io/module: serverless
    app.kubernetes.io/name: serverless
    app.kubernetes.io/instance: serverless-priority-class
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: serverless
value: 2000000
globalDefault: false
description: "Scheduling priority of serverless components. By default, serverless components should not be blocked by unschedulable user workloads."