apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: operator-leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: serverless-operator
    app.kubernetes.io/part-of: serverless-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: serverless-operator
  namespace: system
