apiVersion: operator.kyma-project.io/v1alpha1
kind: Serverless
metadata:
  name: default
  namespace: kyma-system
  annotations:
    serverless.kyma-project.io/buildless-mode: "disabled"
spec:
  dockerRegistry:
    enableInternal: false
