apiVersion: v1
description: Kyma component 'buildless serverless'
name: buildless-serverless
version: 1.0.0
appVersion: "1.9.3"
home: https://kyma-project.io
icon: https://github.com/kyma-project/kyma/blob/main/logo.png?raw=true
dependencies:
