name: build (pull)

on:
  workflow_call:

jobs:
  build-operator:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: serverless-operator
      dockerfile: components/operator/Dockerfile

  build-gitserver:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: gitserver
      dockerfile: Dockerfile
      context: tests/gitserver

  build-serverless-controller:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-controller
      dockerfile: components/serverless/deploy/manager/Dockerfile

  build-serverless-webhook:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-webhook
      dockerfile: components/serverless/deploy/webhook/Dockerfile

  build-serverless-jobinit:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-build-init
      dockerfile: components/serverless/deploy/jobinit/Dockerfile

  build-nodejs18:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs18
      dockerfile: nodejs18/Dockerfile
      context: components/runtimes/nodejs

  build-nodejs20:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs20
      dockerfile: nodejs20/Dockerfile
      context: components/runtimes/nodejs

  build-python39:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python39
      dockerfile: python39/Dockerfile
      context: components/runtimes/python

  build-python312:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python312
      dockerfile: python312/Dockerfile
      context: components/runtimes/python
