name: upgrade tests

on:
  workflow_call:

jobs:
  operator-upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: upgrade test
        run: |
          make -C components/operator deploy-release
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${{ github.sha }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info

  serverless-upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: upgrade test
        run: |
          make install-serverless-latest-release install-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${{ github.sha }}
