name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  operator-lint:
    runs-on: ubuntu-latest
    steps:
      # check
      - uses: ./.github/actions/setup-go
      - uses: actions/checkout@v6
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1
          working-directory: "components/operator"

  serverless-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-libgit2
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1
          working-directory: "components/serverless"

  buildless-serverless-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go
      - uses: actions/checkout@v6
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1
          working-directory: "components/buildless-serverless"
