name: release serverless build
on:
  push:
    tags:
      - '^v?\d+\.\d+\.\d+(?:-.*)?$'
permissions:
  id-token: write
  contents: read

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.sha }}

  build-release-serverless-operator:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: serverless-operator/ga
      dockerfile: components/operator/Dockerfile
      build-arg: PURPOSE=release
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-serverless-controller:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-controller/ga
      dockerfile: components/serverless/deploy/manager/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-serverless-webhook:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-webhook/ga
      dockerfile: components/serverless/deploy/webhook/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-serverless-jobinit:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-build-init/ga
      dockerfile: components/serverless/deploy/jobinit/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-image-nodejs18:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs18/ga
      dockerfile: nodejs18/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-image-nodejs20:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs20/ga
      dockerfile: nodejs20/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-image-python39:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python39/ga
      dockerfile: python39/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-release-image-python312:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python312/ga
      dockerfile: python312/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tag.outputs.tag }}
