name: serverless build (pull)

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image-serverless-controller:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-controller/ga
      dockerfile: components/serverless/deploy/manager/Dockerfile

  build-image-serverless-webhook:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-webhook/ga
      dockerfile: components/serverless/deploy/webhook/Dockerfile

  build-image-serverless-jobinit:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-build-init/ga
      dockerfile: components/serverless/deploy/jobinit/Dockerfile
